/*******************************************************************************
 * Copyright 2013, the Optique Consortium
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * This first version of the R2RML API was developed jointly at the University of Oslo, 
 * the University of Bolzano, La Sapienza University of Rome, and fluid Operations AG, 
 * as part of the Optique project, www.optique-project.eu
 ******************************************************************************/
package eu.optique.r2rml.api.model.impl;

/**
 * Exception type to be thrown when an invalid mapping is found: - no
 * logicalTable - no subjectMap - PredicateObjectMap with PredicaMap but no
 * ObjectMap - RefObjectMap without ParentTriplesMap
 * 
 * @author Timea Bagosi
 * 
 */
public class InvalidR2RMLMappingException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = -1736356498634604004L;

	public InvalidR2RMLMappingException() {
		super();
	}

	public InvalidR2RMLMappingException(String msg) {
		super(msg);
	}
}
